export const about = {
  fullName: "Ckeanu Richer Locson",
  position: "Frontend Developer",
  smallDescription:
    "I focus on building beautiful and interactive interfaces with great experiences.",
  bigDescription1:
    "I'm a Computer Science graduate and I specialize in building user interfaces for web-based applications using other tools and libraries to make my project more solid and efficient. Utilizing my skills in web development is crucial to ensure that the service I deliver meets the standard of a company or my client.",
  bigDescription2:
    "I'm still looking for an opportunity where I can use and enhance my skills and knowledge for organizational and personal growth.",
  homeAddress: "Zamboanga City, Philippines",
  emailAddress: "ckeandev@gmail.com",
  contactNumber: "0955 210 1316",

  githubLink: "https://github.com/ckeanudev",
  linkedInLink: "https://www.linkedin.com/in/ckeanuuu/",
  instagramLink: "https://www.instagram.com/ckeanuuu/",
  facebookLink: "https://www.facebook.com/ckeanuuu/",
};

export const experience = [
  {
    position: `Front End Developer`,
    company: `AKA Software Inc.`,
    timeline: `2023 — PRESENT`,
    description: `Working with the team to develop and improve major and minor features of AKA's web apps.`,
    tools: [
      "React",
      "Tailwind CSS",
      "SCSS",
      "JavaScript",
      "TypeScript",
      "AG Grid",
      "Redux",
      "Prime React",
      "Visual Studio Code",
    ],
  },
];

export const featuredProjects = [
  {
    title: `Showjects`,
    description: `A platform where you can showcase your personal software development projects where other developers can see, comment, review your source code and give feedback about your projects to help you get better.`,
    img: `/images/Featured Projects/F2.png`,
    liveUrl: `https://showjects.vercel.app/`,
    sourceUrl: `https://github.com/ckeanudev/showjects`,
    tools: [
      "React",
      "TypeScript",
      "Next",
      "Tailwind CSS",
      "shadcn/ui",
      "Clerk",
      "MongoDB",
      "Zod",
      "Uploadthing",
    ],
    status: {
      underDevelopment: false,
      improving: true,
      finished: false,
    },
    year: 2023,
  },
  {
    title: `AniBrary`,
    description: `A website containing collections of anime provided by Jikan API an open-source PHP & REST API for the most active online anime + manga community and database. This website has all the information of your favorite anime and characters.`,
    img: `/images/Featured Projects/F1.png`,
    liveUrl: `https://anibrary.vercel.app/`,
    sourceUrl: `https://github.com/ckeanudev/anibrary`,
    tools: [
      "React",
      "TypeScript",
      "Next",
      "Tailwind CSS",
      "shadcn/ui",
      "React Query",
      "API",
    ],
    status: {
      underDevelopment: false,
      improving: false,
      finished: true,
    },
    year: 2023,
  },
];

export const bigProjects = [
  // {
  //   title: `Web Based Grading System`,
  //   tools: [`React`, `Next`, `Sass`, `MySQL`, `Axios`, `Framer Motion`],
  //   description: `I built a full-stack web-based grading system for a specific school here in Zamboanga City, Philippines. Where teachers/faculties manage the grades of the students, and students can see their grades by logging in to their accounts. I took this opportunity to explore more about Next since it provides additional structure, features, and optimizations for your React application.`,
  //   year: 2023,
  //   purpose: `Freelance`,
  // },
  {
    title: `Apprabic: Mobile Application`,
    tools: [`Unity 3D`, `C#`, `Adobe Illustrator`],
    description: `I built a full-stack mobile application for our thesis in our Computer Science course. The mobile app helps children to learn Arabic letters and numbers, especially in writing, pronunciation, and arranging in order. I took this opportunity to learn Unity 3D since I wanted to build a video game ever since I started programming.`,
    year: 2023,
    purpose: `Thesis`,
  },
  {
    title: `Munta`,
    tools: [`Flutter`, `Firebase`],
    description: `We built this mobile app for our Capstone Project in DICT Cross-Platform Coding Bootcamp Using Flutter. My job here was to turn the design from Figma into a functional user interface while my team focused on the backend with Firebase. After presenting the Capstone Project, we've won the "Best in User Interface (UI) and Design", and "Most Creative awards". This project inspired by a mobile app called "Maxim".`,
    year: 2022,
    purpose: `Coding Bootcamp`,
  },
  {
    title: `Online Hotel Booking System`,
    tools: [`React`, `Node`, `Express`, `MySQL`, `Axios`, `Framer Motion`],
    description: `I built a full-stack web-based online booking system for a specific hotel here in Zamboanga City, Philippines. The system helps customers book or reserve a room online without going to the hotel. I took this opportunity to learn React, Node, Express, and MySQL to explore and improve my skills for my future career. I built this project to comply our Software Engineering project in my Computer Science course.`,
    year: 2022,
    purpose: `Software Engineering`,
  },
];

export const smallProjects = [
  {
    title: "Easybank Landing Page",
    imgSrc: `/images/Small Projects/sm15.png`,
    tools: ["Astro", "React", "Tailwind CSS"],
    sourceUrl: `https://github.com/ckeanudev/frontendmentor-easybank`,
    liveUrl: `https://frontendmentor-easybank-six.vercel.app/`,
    year: "2023",
  },
  {
    title: "Ecommerce Product",
    imgSrc: `/images/Small Projects/sm14.png`,
    tools: ["React"],
    sourceUrl: `https://github.com/ckeanudev/frontend-mentor-ecommerce-product`,
    liveUrl: `https://frontend-mentor-ecommerce-product.vercel.app`,
    year: "2023",
  },
  {
    title: "Results Summary Component",
    imgSrc: `/images/Small Projects/sm13.png`,
    tools: ["HTML", "CSS"],
    sourceUrl: `https://github.com/ckeanudev/frontend-mentor-results-summary-component`,
    liveUrl: `https://frontend-mentor-results-summary-component-two.vercel.app`,
    year: "2023",
  },
  {
    title: "Rock, Paper, Scissors Game",
    imgSrc: `/images/Small Projects/sm12.png`,
    tools: ["React"],
    sourceUrl: `https://github.com/ckeanudev/frontend-mentor-rock-paper-scissors-game`,
    liveUrl: `https://ckeanu-frontend-mentor-game.netlify.app`,
    year: "2022",
  },
  {
    title: "REST Countries API",
    imgSrc: `/images/Small Projects/sm11.png`,
    tools: ["React", "API"],
    sourceUrl: `https://github.com/ckeanudev/dev-rest-country-api`,
    liveUrl: `https://ckeanu-country-api.netlify.app`,
    year: "2022",
  },
  {
    title: "Job Listings w/ Filtering",
    imgSrc: `/images/Small Projects/sm10.png`,
    tools: ["React"],
    sourceUrl: `https://github.com/ckeanudev/frontend-mentor-job-listing`,
    liveUrl: `https://ckeanu-job-listing.netlify.app`,
    year: "2022",
  },
  {
    title: "Free Games Site",
    imgSrc: `/images/Small Projects/sm9.png`,
    tools: ["React", "API"],
    sourceUrl: `https://github.com/ckeanudev/dev-free-games-list`,
    liveUrl: `https://ckeanu-free-games.netlify.app`,
    year: "2022",
  },
  {
    title: "Small Meal App",
    imgSrc: `/images/Small Projects/sm8.png`,
    tools: ["React", "API"],
    sourceUrl: `https://github.com/ckeanudev/dev-react-meal-app`,
    liveUrl: `https://ckeanu-meal-app.netlify.app`,
    year: "2022",
  },
  {
    title: "COVID-19 Case Tracker App",
    imgSrc: `/images/Small Projects/sm7.png`,
    tools: ["React", "API"],
    sourceUrl: `https://github.com/ckeanudev/dev-covid-19-tracker-system`,
    liveUrl: `https://ckeanu-covid-19-tracker-system.netlify.app`,
    year: "2022",
  },
  {
    title: "Cryptocurrency Price Tracker App",
    imgSrc: `/images/Small Projects/sm6.png`,
    tools: ["React", "API"],
    sourceUrl: `https://github.com/ckeanudev/dev-crypto-price-tracker`,
    liveUrl: `https://ckeanu-crypto-price-tracker.netlify.app`,
    year: "2022",
  },

  {
    title: "Huddle Landing Page",
    imgSrc: `/images/Small Projects/sm4.png`,
    tools: ["HTML", "CSS"],
    sourceUrl: `https://github.com/ckeanudev/Huddle-landing-page`,
    liveUrl: `https://huddle-landing-page-ckeanu.netlify.app`,
    year: "2022",
  },
  {
    title: "Project Tracking Intro Component",
    imgSrc: `/images/Small Projects/sm3.png`,
    tools: ["HTML", "CSS"],
    sourceUrl: `https://github.com/ckeanudev/Project-tracking-intro-component`,
    liveUrl: `https://project-tracking-intro-component-ckeanu.netlify.app`,
    year: "2022",
  },

  {
    title: "NFT Preview Card Component",
    imgSrc: `/images/Small Projects/sm2.png`,
    tools: ["HTML", "CSS"],
    sourceUrl: `https://github.com/ckeanudev/NFT-preview-card-component`,
    liveUrl: `https://nft-preview-card-component-ckeanu.netlify.app`,
    year: "2022",
  },
  {
    title: "Order Summary Card",
    imgSrc: `/images/Small Projects/sm1.png`,
    tools: ["HTML", "CSS"],
    sourceUrl: `https://github.com/ckeanudev/Order-summary-card`,
    liveUrl: `https://order-summary-card-ckeanu.netlify.app`,
    year: "2022",
  },
  {
    title: "To-Do List App",
    imgSrc: `/images/Small Projects/sm5.png`,
    tools: ["HTML", "CSS", "JS"],
    sourceUrl: `https://github.com/ckeanudev/vanilla-javascript-to-do-list`,
    liveUrl: `https://to-do-list-ckeanu.netlify.app`,
    year: "2021",
  },
];
